/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: f20af335fb9ad54b392182442efac584)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Merchant";
	}
	interface Env {
		LOADER: WorkerLoader;
		AI: Ai;
		MERCHANT: DurableObjectNamespace<import("./src/server").Merchant>;
		GOOGLE_GENERATIVE_AI_API_KEY: string;
		FB_VERIFY_TOKEN: string;
		FB_PAGE_ACCESS_TOKEN: string;
		FB_APP_SECRET: string;
	}
}
interface Env extends Cloudflare.Env {}
